worker:
  period: 5m # run every 5 minutes, 30s = run every 30 seconds
ldap:
  url: "ldap://dc4:389"
  baseDn: "DC=intranet,DC=ydp"
  user: "timemanager@intranet.ydp"
  password: "PASSWORD"
  validationGroup: StaticGroup # group which members are reset (read then written) to check write permission
logging:
  level: INFO
