db:
  driverClass: "org.h2.Driver"
  url: "jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1"
  user: ""
  properties:
    "hibernate.dialect": "org.hibernate.dialect.H2Dialect"
    "hibernate.hbm2ddl.auto": "update"
    "hibernate.show_sql": true
    "hibernate.format_sql": true
worker:
  period: 5s
